### ISSUE TITLE
findOneAndUpdate is not translated

### ISSUE THREAD

**Issue by krzysztofpniak** [matteodelabre/mongoose-beautiful-unique-validation#27]
Does not translate error when save is performed from findOneAndUpdate.

**Comment by matteodelabre** [comment]
Hello @krzysztofpniak, thanks for the report. I just published version `5.1.0` which should fix your problem. However, note that the error will not provide the list of fields that made the constraint fail, because the driver does not provide it.

If you need that information, please first find your model, then save it using this kind of code (from Mongoose docs):

```js
Model.findById(id, function (err, doc) {
  if (err) ..
  doc.name = 'jason borne';
  doc.save(callback);
});
```
